
apiVersion: batch/v1
kind: Job
metadata: 
  name: hello-world-conplitions
spec:
  backoffLimit: 3
  completions: 10
  template:
    metadata:
      name: hello-world-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: hello-world-container
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["echo 'Hello World!;  sleep 3'"]
