apiVersion: v1
kind: Pod
metadata:
  name: init-container-pod
spec: 
  initContainers:
  - name: my-init-container
    image: busybox:latest
    command: ["sleep", "15"]
  containers:
  - name: nginx-container
    image: nginx:latest